### ISSUE TITLE
CNBC Added Auth?

### ISSUE THREAD

**Issue by NHLGames** [endwall2/endstream#2]
Looks like the current CNBC link is not working:

https://1674331492.rsc.cdn77.org/LS-ATL-54548-14/tracks-v1a1/mono.m3u8

but I've found one elsewhere that seems to include some kind of auth token (therefore I'm not sure if it will last, will have to keep an eye on it over a period of a few days):

https://1674331492.rsc.cdn77.org/jjgi7gf0qkoQqeeLsXQxBA==,1585335556/LS-ATL-54548-14/tracks-v1a1/mono.m3u8

Another alternative, although seems even more unlikely to last:

https://peer2.ustv.to/CNBC/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8yNy8yMDIwIDQ6MTM6MzcgUE0maGFzaF92YWx1ZT04Y0t2QzIxcUlnTC9sZkhlTjN0TStBPT0mdmFsaWRtaW51dGVzPTI0MCZpZD0w

**Comment by endwall2** [comment]
Thanks for the stream options.  I'm turfing it out of mainline.  I have replaced these channels with the CBSN local channels.  You can add your own streams on page 2 or 3.  The pirate streams never last, even official streams like PBS shut it down when they get too much traffic.  I update the dead streams when it strikes me to look, if I can't solve it I turf the channels after a couple of months (delete them). Thanks for the info / help.
